### ISSUE TITLE
Unable to update Roon Server 

### ISSUE THREAD

**Issue by infinitenewworld** [steefdebruijn/docker-roonserver#30]
Everything is working perfectly however I'm unable to update the Roon Server, I always get this error:

"There was an error checking for an update."

I am running this on a QNAP device. Here is what I'm seeing in the logs:

04/05 09:27:57 Trace: [appupdater] initial check for updates
04/05 09:27:57 Debug: [base/updater] Checking for updates: https://updates.roonlabs.net/update/?v=2&serial=4270FE73-F52F-42FF-B994-4C72794E85B2&userid=3dec8295-ef49-483b-b8e0-bbc6aa9fce4c&platform=linuxx64&product=RoonServer&branding=roon&curbranch=production&version=200001388&branch=production&coredeviceid=15f2d400-ebb7-4787-b0bb-ef8182aae3ea&deviceid=15f2d400-ebb7-4787-b0bb-ef8182aae3ea&osversion=Linux+5.10.60-qnap&os64bit=true
04/05 09:27:57 Debug: [easyhttp] [28] POST to https://api.roonlabs.net/roonmobile/1/cores/announce returned after 247 ms, status code: 200, request body size: 936 B
04/05 09:27:57 Debug: [easyhttp] [27] GET to https://api.roonlabs.net/updates/update/?v=2&serial=4270FE73-F52F-42FF-B994-4C72794E85B2&userid=3dec8295-ef49-483b-b8e0-bbc6aa9fce4c&platform=linuxx64&product=RoonServer&branding=roon&curbranch=production&version=200001388&branch=production&coredeviceid=15f2d400-ebb7-4787-b0bb-ef8182aae3ea&deviceid=15f2d400-ebb7-4787-b0bb-ef8182aae3ea&osversion=Linux+5.10.60-qnap&os64bit=true returned after 358 ms, status code: 200, request body size: 0 B
04/05 09:27:57 Debug: [base/updater] Update response: priority=compatible
04/05 09:27:57 Debug: [base/updater] Update response: updateurl=http://download.roonlabs.net/updates/production/RoonServer_linuxx64_200001392.tar.bz2
04/05 09:27:57 Debug: [base/updater] Update response: machineversion=200001392
04/05 09:27:57 Debug: [base/updater] Update response: displayversion=2.0 (build 1392) production
04/05 09:27:57 Debug: [base/updater] Update response: branch=production
04/05 09:27:57 Debug: [base/updater] Update response: type=roon
04/05 09:27:57 Debug: [base/updater] Update response: changelog=
04/05 09:27:57 Debug: [appupdater] Update is available: 2.0 (build 1392) production, Compatible
04/05 09:27:58 Debug: [easyhttp] [29] POST to https://api.roonlabs.net/roonmobile/1/cores/announce returned after 146 ms, status code: 200, request body size: 939 B
04/05 09:27:58 Debug: [easyhttp] [30] POST to https://api.roonlabs.net/roonmobile/1/cores/announce returned after 152 ms, status code: 200, request body size: 939 B
04/05 09:27:58 Info: [stats] 4900mb Virtual, 134mb Physical, 18mb Managed, 267 Handles, 69 Threads
04/05 09:28:13 Info: [stats] 4900mb Virtual, 134mb Physical, 22mb Managed, 270 Handles, 67 Threads
04/05 09:28:21 Info: [mobile] GOT HTTP API /hello
04/05 09:28:21 Trace: [mobile] Got Hello Request body={"coreId":"15f2d400-ebb7-4787-b0bb-ef8182aae3ea"}
04/05 09:28:28 Info: [stats] 4675mb Virtual, 136mb Physical, 17mb Managed, 270 Handles, 40 Threads
04/05 09:28:43 Info: [stats] 4699mb Virtual, 138mb Physical, 17mb Managed, 271 Handles, 44 Threads
04/05 09:28:58 Info: [stats] 4699mb Virtual, 139mb Physical, 16mb Managed, 268 Handles, 41 Threads
04/05 09:29:13 Info: [stats] 4699mb Virtual, 138mb Physical, 19mb Managed, 270 Handles, 41 Threads
04/05 09:29:28 Info: [stats] 4707mb Virtual, 138mb Physical, 17mb Managed, 269 Handles, 45 Threads
04/05 09:29:37 Error: [appupdater] While downloading update: System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
04/05 09:29:38 Debug: [easyhttp] [32] POST to https://api.roonlabs.net/roonmobile/1/cores/announce returned after 139 ms, status code: 200, request body size: 933 B
04/05 09:29:43 Info: [stats] 4755mb Virtual, 138mb Physical, 17mb Managed, 268 Handles, 50 Threads
04/05 09:29:58 Info: [stats] 4683mb Virtual, 138mb Physical, 16mb Managed, 268 Handles, 39 Threads
04/05 09:30:13 Info: [stats] 4683mb Virtual, 138mb Physical, 16mb Managed, 268 Handles, 39 Threads
04/05 09:30:28 Info: [stats] 4683mb Virtual, 138mb Physical, 18mb Managed, 269 Handles, 41 Threads
04/05 09:30:43 Info: [stats] 4699mb Virtual, 137mb Physical, 19mb Managed, 268 Handles, 44 Threads
04/05 09:30:58 Info: [stats] 4691mb Virtual, 137mb Physical, 17mb Managed, 270 Handles, 40 Threads
04/05 09:31:13 Info: [stats] 4691mb Virtual, 137mb Physical, 18mb Managed, 273 Handles, 41 Threads
04/05 09:31:28 Info: [stats] 4691mb Virtual, 136mb Physical, 16mb Managed, 267 Handles, 39 Threads
04/05 09:31:43 Info: [stats] 4707mb Virtual, 136mb Physical, 18mb Managed, 269 Handles, 44 Threads
04/05 09:31:58 Info: [stats] 4683mb Virtual, 136mb Physical, 18mb Managed, 269 Handles, 39 Threads
04/05 09:32:13 Info: [stats] 4683mb Virtual, 136mb Physical, 16mb Managed, 268 Handles, 39 Threads
04/05 09:32:25 Info: [mobile] GOT HTTP API /portverify/9105661d-a981-4942-b492-97cad0439bfa
04/05 09:32:25 Trace: [mobile] Got PortVerify Request from_guid=9105661d-a981-4942-b492-97cad0439bfa
04/05 09:32:25 Trace: [mobile]     Could not find to_guid for from_guid: 9105661d-a981-4942-b492-97cad0439bfa
04/05 09:32:28 Info: [stats] 4683mb Virtual, 136mb Physical, 18mb Managed, 269 Handles, 40 Threads
04/05 09:32:28 Trace: [broker/accounts] [heartbeat] now=04/05/2024 16:32:28 nextauthrefresh=04/05/2024 17:27:30 nextmachineallocate=04/05/2024 20:27:28
04/05 09:32:30 Info: [mobile] GOT HTTP API /hello
04/05 09:32:30 Trace: [mobile] Got Hello Request body={"coreId":"15f2d400-ebb7-4787-b0bb-ef8182aae3ea"}
04/05 09:32:43 Info: [stats] 4699mb Virtual, 138mb Physical, 15mb Managed, 269 Handles, 43 Threads
04/05 09:32:58 Info: [stats] 4699mb Virtual, 138mb Physical, 15mb Managed, 270 Handles, 40 Threads
04/05 09:33:13 Info: [stats] 4675mb Virtual, 139mb Physical, 17mb Managed, 267 Handles, 38 Threads
04/05 09:33:28 Info: [stats] 4675mb Virtual, 139mb Physical, 16mb Managed, 269 Handles, 38 Threads
04/05 09:33:43 Info: [stats] 4755mb Virtual, 137mb Physical, 15mb Managed, 269 Handles, 50 Threads
04/05 09:33:58 Info: [stats] 4691mb Virtual, 139mb Physical, 17mb Managed, 266 Handles, 39 Threads

Any ideas? Would love to get this working! Thanks :)

**Comment by steefdebruijn** [comment]
Simplest thing to try is remove docker container and app volume (not your music, backup folders!!) and try again. At least it will download latest version again on first startup.
